version: '3.4'

services:
  bookdb:
    image: mongo

  userdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  rabbitmq:
    image: rabbitmq:3-management-alpine

  book.api:
    image: ${DOCKER_REGISTRY-}bookapi
    build:
      context: .
      dockerfile: Services/Book/Book.API/Dockerfile

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  redis_data:
  rabbit_data:
