version: '3.4'

services:
  bookdb:
    image: mongo

  userdb:
    image: mcr.microsoft.com/mssql/server

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  book.api:
    image: ${DOCKER_REGISTRY-}bookapi
    build:
      context: .
      dockerfile: Services/Book/Book.API/Dockerfile

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data: