version: '3.4'

services:
  bookdb:
    container_name: bookdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  userdb:
    container_name: userdb
    environment:
        SA_PASSWORD: "Juhil.BS@123"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1434:1433"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
 
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "Juhil.BS@123"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin@123
    restart: always
    ports:
      - "5050:80"
    volumes:
      - "pgadmin_data:/root/.pgadmin"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  book.api:
    container_name: book.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://bookdb:27017"
      - "RabbitMq:HostUrl=amqp://guest:guest@rabbitmq"
    ports:
      - "4000:80"

  user.api:
    container_name: user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=userdb;Database=Userdb;User Id=sa;Password=Juhil.BS@123;MultipleActiveResultSets=True;TrustServerCertificate=True"
    ports:
      - "4001:80"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "RabbitMq:HostUrl=amqp://guest:guest@rabbitmq"
    ports:
      - "4002:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin@123"
    ports:
      - "4003:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin@123"
    ports:
      - "4004:80"

  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=orderdb;Database=OrderDb;User Id=sa;Password=Juhil.BS@123;MultipleActiveResultSets=True;TrustServerCertificate=True"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq"
    ports:
      - "4005:80"